name: validator
on:
  pull_request:
    types: [ready_for_review]
jobs:
  validate_title:
    name: validate_title
    runs-on: ubuntu-latest
    steps:
      - name: validate title
        # shell: bash
        # run: ../validate.sh ${{ github.event.pull_request.title }}
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const REGEX = new RegExp(/^(feat|fix|docs|style|refactor|test|chore)\(.+\): .+/);
            if (!REGEX.test(context.payload.pull_request.title)) {
              await github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '正しいタイトルにしてください。\nよろしくお願いします。'
              })
              await github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['please fix title!']
              })
            }