name: validator
on:
  pull_request:
    types: [ready_for_review]
jobs:
  validate_title:
    name: validate_title
    runs-on: ubuntu-latest
    steps:
      - name: validate title
        # shell: bash
        # run: ../validate.sh ${{ github.event.pull_request.title }}
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '正しいタイトルにしてください'
            })